apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    name: backend-deploy
    app: cvc
spec:
  replicas: 3
  selectors:
    matchLabels:
      tier: backend-pod
      app: cvc
  template:
    metadata:
      name: backend
      labels:
        tier: backend-pod
        app: cvc
      spec:
        containers:
          - name: cvc-backend
            image: kuunika/cvc-backend
            envFrom:
              - secretRef:
                  name: cvc-backend-secrets
        
