apiVersion: apps/v1
kind: Service
metadata:
  name: cvc-api-service
  labels:
    name: cvc-api-service
    app: cvc
specs: 
  selectors:
    matchLabels:
      tier: backend
      app: cvc 
  ports:
    port: 80
    targetPort: 3000